---
swagger: "2.0"
info:
  description: |
    
  version: "1.0.0"
  title: "Authentication"
  termsOfService: ""
basePath: "/api/v1"
tags:
- name: Authentication
schemes:
- "http"
paths:
  /auth/register:
    post:
      tags:
      - Authentication
      summary: "Add/Update phone number"
      description: "Account Registration"
      operationId: "register"
      consumes:
      - "application/json"
      produces:
      - "applicaion/json"
      parameters:
      - in: "body"
        name: "body"
        description: Registration
        required: true
        schema:
          $ref: "#/definitions/Register"
      responses:
        200:
          description: "Response on successful request"
      x-swagger-router-controller: "User"
  /auth/login:
    post:
      tags:
      - Authentication
      summary: "User Login"
      description: "User Login"
      operationId: "Login"
      consumes:
      - "application/json"
      produces:
      - "applicaion/json"
      parameters:
      - in: "body"
        name: "body"
        description: User Login
        required: true
        schema:
          $ref: "#/definitions/Login"
      responses:
        200:
          description: "Response on successful request"
      x-swagger-router-controller: "User"
  /auth/verify-email:
    post:
      tags:
      - Authentication
      summary: "Email Verification"
      description: "Email Verification"
      operationId: "Email Varification"
      consumes:
      - "application/json"
      produces:
      - "applicaion/json"
      parameters:
      - in: "body"
        name: "body"
        description: Email Verification
        required: true
        schema:
          $ref: "#/definitions/EmailVerify"
      responses:
        200:
          description: "Response on successful request"
      x-swagger-router-controller: "User"    


definitions:
  Register:
    type: object
    required:
    - "email"
    - "firstname"
    - "lastname"
    - "password"
    - "phone"
    properties:
      firstname:
        type: string
        description: First name
      lastname:
        type: string
        description: Last name
      email:
        type: "string"
        description: Email
      password:
        type: "string"
        description: |
          Password
      phone:
        type: number
        description: Contact number
  Login:
    type: object
    required:
    - "email"
    - "password"
    properties:
      email:
        type: "string"
        description: Email
      password:
        type: "string"
        description: |
          Password
  EmailVerify:
    type: object
    required:
    - "code"
    properties:
      code:
        type: "string"
        description: Verification code
      