---
swagger: "2.0"
info:
  description: |
    
  version: "1.0.0"
  title: "Authentication"
  termsOfService: ""
basePath: "/api/v1"
tags:
- name: Authentication
schemes:
- "http"
paths:
  /auth/register:
    post:
      tags:
      - Authentication
      summary: "Add/Update phone number"
      description: "Account Registration"
      operationId: "register"
      consumes:
      - "application/json"
      produces:
      - "applicaion/json"
      parameters:
      - in: "body"
        name: "body"
        description: Registration
        required: true
        schema:
          $ref: "#/definitions/Register"
      responses:
        200:
          description: "Response on successful request"
      x-swagger-router-controller: "User"
  /auth/login:
    post:
      tags:
      - Authentication
      summary: "User Login"
      description: "User Login"
      operationId: "Login"
      consumes:
      - "application/json"
      produces:
      - "applicaion/json"
      parameters:
      - in: "body"
        name: "body"
        description: User Login
        required: true
        schema:
          $ref: "#/definitions/Login"
      responses:
        200:
          description: "Response on successful request"
      x-swagger-router-controller: "User"
  /auth/verify-email:
    post:
      tags:
      - Authentication
      summary: "Email Verification"
      description: "Email Verification"
      operationId: "Email Varification"
      consumes:
      - "application/json"
      produces:
      - "applicaion/json"
      parameters:
      - in: "body"
        name: "body"
        description: Email Verification
        required: true
        schema:
          $ref: "#/definitions/EmailVerify"
      responses:
        200:
          description: "Response on successful request"
      x-swagger-router-controller: "User"
  /auth/forgot-password:
    post:
      tags:
      - Authentication
      summary: "Forgot Password"
      description: "Forgot Password"
      operationId: "Forgot Password"
      consumes:
      - "application/json"
      produces:
      - "applicaion/json"
      parameters:
      - in: "body"
        name: "body"
        description: Forgot Password
        required: true
        schema:
          $ref: "#/definitions/ForgotPassword"
      responses:
        200:
          description: "Response on successful request"
      x-swagger-router-controller: "User"
  /auth/change-forgot-password:
    post:
      tags:
      - Authentication
      summary: "Forgot Password"
      description: "Forgot Password"
      operationId: "Forgot Password"
      consumes:
      - "application/json"
      produces:
      - "applicaion/json"
      parameters:
      - in: "body"
        name: "body"
        description: Forgot Password
        required: true
        schema:
          $ref: "#/definitions/ChangeForgotPassword"
      responses:
        200:
          description: "Response on successful request"
      x-swagger-router-controller: "User"
  /auth/facebook:
    get:
      summary: Facebook access token validation
      description: Facebook access token validation
      tags:
      - "Authentication"
      parameters:
        - in: query
          name: access_token
          type: string
          required: false
          description: Facebook Access Token
      responses:
        200:
          description: OK
  /profile/change-password:
    post:
      tags:
      - Profile
      summary: "Change Password"
      description: "Change Password"
      operationId: "Change Password"
      consumes:
      - "application/json"
      produces:
      - "applicaion/json"
      parameters:
      - name: "x-access-token"
        in: "header"
        description: Authentication Token
        type: "string"
        required: true
      - in: "body"
        name: "body"
        description: Change Password
        required: true
        schema:
          $ref: "#/definitions/ChangePassword"
      responses:
        200:
          description: "Response on successful request"
      x-swagger-router-controller: "User"
  /profile/update-profile:
    post:
      tags:
      - Profile
      summary: "Update Profile"
      description: "Update Profile"
      operationId: "Update Profile"
      consumes:
      - "application/json"
      produces:
      - "applicaion/json"
      parameters:
      - name: "x-access-token"
        in: "header"
        description: Authentication Token
        type: "string"
        required: true
      - in: "body"
        name: "body"
        description: Change Password
        required: true
        schema:
          $ref: "#/definitions/UpdateProfile"
      responses:
        200:
          description: "Response on successful request"
      x-swagger-router-controller: "User"
  /profile/me:
    get:
      summary: Get Profile Details
      description: Get Profile Details
      tags:
      - "Profile"
      parameters:
        - name: "x-access-token"
          in: "header"
          description: Authentication Token
          type: "string"
          required: true
      responses:
        200:
          description: OK                
                          


definitions:
  Register:
    type: object
    required:
    - "email"
    - "firstname"
    - "lastname"
    - "password"
    - "phone"
    properties:
      firstname:
        type: string
        description: First name
      lastname:
        type: string
        description: Last name
      email:
        type: "string"
        description: Email
      password:
        type: "string"
        description: |
          Password
      phone:
        type: number
        description: Contact number
  Login:
    type: object
    required:
    - "email"
    - "password"
    properties:
      email:
        type: "string"
        description: Email
      password:
        type: "string"
        description: |
          Password
  EmailVerify:
    type: object
    required:
    - "code"
    properties:
      code:
        type: "string"
        description: Verification code
  ForgotPassword:
    type: object
    required:
    - "email"
    properties:
      email:
        type: "string"
        description: Fogot Password Email
  ChangeForgotPassword:
    type: object
    required:
    - "code"
    - "password"
    properties:
      code:
        type: "string"
        description: Fogot Password Code
      password:
        type: "string"
        description: New Password
  ChangePassword:
    type: object
    required:
    - "old_password"
    - "new_password"
    properties:
      old_password:
        type: "string"
        description: Old Password
      new_password:
        type: "string"
        description: New Password
  UpdateProfile:
    type: object
    required:
    - "firstname"
    - "lastname"
    - "phone"
    - "about"
    - "location"
    - "gender"
    properties:
      firstname:
        type: string
        description: First name
      lastname:
        type: string
        description: Last name
      about:
        type: "string"
        description: About
      location:
        type: "string"
        description: |
          Location
      phone:
        type: string
        description: Contact number
      gender:
        type: string
        description: Gender                            
      